name: ci

on: 
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format:check

      - name: Check dependencies
        run: yarn depcheck

      - name: Compile
        run: yarn compile

      - name: Lint monorepo
        run: yarn lint:monorepo

      - name: Run tests
        run: yarn test --ci

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff